spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PWD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  output:
    ansi:
      enabled: always
  redis:
    host: localhost
    port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_ID}
            client-secret: ${OAUTH_GOOGLE_SECRET}
            scope:
              - email
              - profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google # 기본값
server:
  servlet:
    encoding:
      charset: UTF-8
jwt:
  secret-key: qwe123qwe123qwe123qwe123qwe123qwe123qwe123qwe123qwe123qwe123qwe123qwe123qwe123qwe123qwe123qwe123
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 360
logging:
  level:
    org:
      springframework:
        orm:
          jpa: debug
    root: info