spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true
    defer-datasource-initialization: true
  output:
    ansi:
      enabled: always
  redis:
    host: localhost
    port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: secret
            client-secret: secret
            scope:
              - email
              - profile
  sql:
    init:
      mode: embedded
server:
  servlet:
    encoding:
      charset: UTF-8
jwt:
  secret-key: qwe123qwe123qwe123qwe123qwe123qwe123qwe123qwe123qwe123qwe123qwe123qwe123qwe123qwe123qwe123qwe123
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 360
cloud:
  aws:
    credentials:
      accessKey: secret
      secretKey: secret
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucketName: lookatme-image-bucket
logging:
  level:
    org:
      springframework:
        orm:
          jpa: debug
    root: info

---
# 무중단 배포를 위한 설정 (8081 포트 설정)
spring:
  config:
    activate:
      on-profile: real1
server:
  port: 8081

---
# 무중단 배포를 위한 설정 (8082 포트 설정)
spring:
  config:
    activate:
      on-profile: real2
server:
  port: 8082

