# Docker Image build & push - 다른 Workflow가 해당 Workflow를 호출해서 사용하는 방식
name: Look At Me Docker build

on:
  workflow_call:
    inputs:
      message:
        description: 'Test Message'
        default: 'Hello Docker!'
        required: true
        type: string

jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo The message is ${{ inputs.message }}
