name: Gradle Build

on:
  workflow_call:

jobs:
  Gradle-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        shell: bash
        working-directory: ./server # 작업 디렉토리 지정

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Add permission to gradlew & Build
        run: |
          chmod +x ./gradlew
          ./gradlew clean build --stacktrace

      - uses: actions/upload-artifact@v3
        name: Build File Upload
        with:
          name: build-jar-file
          path: build/libs/*.jar
